on: push
jobs: 
  build-node: 
    runs-on: ubuntu-latest
    container: node:18
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm install -g nodemon ts-node
      - run: npm start

      - name: build and push docker image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: jishnu79/typescript
          registry: docker.io
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}